// Copyright (c) the JPEG XL Project Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#![allow(clippy::excessive_precision)]

use std::f32::consts::PI;

use num_traits::abs;

use super::eval_rational_poly;

const POW2F_NUMER_COEFFS: [f32; 3] = [1.01749063e1, 4.88687798e1, 9.85506591e1];
const POW2F_DENOM_COEFFS: [f32; 4] = [2.10242958e-1, -2.22328856e-2, -1.94414990e1, 9.85506633e1];

#[inline]
pub fn fast_cos(x: f32) -> f32 {
    // Step 1: range reduction to [0, 2pi)
    let pi2 = PI * 2.0;
    let pi2_inv = 0.5 / PI;
    let npi2 = (x * pi2_inv).floor() * pi2;
    let xmodpi2 = x - npi2;
    // Step 2: range reduction to [0, pi]
    let x_pi = xmodpi2.min(pi2 - xmodpi2);
    // Step 3: range reduction to [0, pi/2]
    let above_pihalf = x_pi >= PI / 2.0;
    let x_pihalf = if above_pihalf { PI - x_pi } else { x_pi };
    // Step 4: Taylor-like approximation, scaled by 2**0.75 to make angle
    // duplication steps faster, on x/4.
    let xs = x_pihalf * 0.25;
    let x2 = xs * xs;
    let x4 = x2 * x2;
    let cosx_prescaling = x4 * 0.06960438 + (x2 * -0.84087373 + 1.68179268);
    // Step 5: angle duplication.
    let cosx_scale1 = cosx_prescaling * cosx_prescaling - 1.414213562;
    let cosx_scale2 = cosx_scale1 * cosx_scale1 - 1.0;
    // Step 6: change sign if needed.
    if above_pihalf {
        -cosx_scale2
    } else {
        cosx_scale2
    }
}

#[inline]
pub fn fast_erff(x: f32) -> f32 {
    // Formula from
    // https://en.wikipedia.org/wiki/Error_function#Numerical_approximations
    // but constants have been recomputed.
    let absx = abs(x);
    // Compute 1 - 1 / ((((x * a + b) * x + c) * x + d) * x + 1)**4
    let denom1 = absx * 7.77394369e-02 + 2.05260015e-04;
    let denom2 = denom1 * absx + 2.32120216e-01;
    let denom3 = denom2 * absx + 2.77820801e-01;
    let denom4 = denom3 * absx + 1.0;
    let denom5 = denom4 * denom4;
    let inv_denom5 = 1.0 / denom5;
    let result = -inv_denom5 * inv_denom5 + 1.0;
    result.copysign(x)
}

#[inline]
pub fn fast_pow2f(x: f32) -> f32 {
    let x_floor = x.floor();
    let exp = f32::from_bits(((x_floor as i32 + 127) as u32) << 23);
    let frac = x - x_floor;

    let num = frac + POW2F_NUMER_COEFFS[0];
    let num = num * frac + POW2F_NUMER_COEFFS[1];
    let num = num * frac + POW2F_NUMER_COEFFS[2];
    let num = num * exp;

    let den = POW2F_DENOM_COEFFS[0] * frac + POW2F_DENOM_COEFFS[1];
    let den = den * frac + POW2F_DENOM_COEFFS[2];
    let den = den * frac + POW2F_DENOM_COEFFS[3];

    num / den
}

const LOG2F_P: [f32; 3] = [
    -1.8503833400518310e-6,
    1.4287160470083755,
    7.4245873327820566e-1,
];
const LOG2F_Q: [f32; 3] = [
    9.9032814277590719e-1,
    1.0096718572241148,
    1.7409343003366853e-1,
];

#[inline]
pub fn fast_log2f(x: f32) -> f32 {
    let x_bits = x.to_bits() as i32;
    let exp_bits = x_bits.wrapping_sub(0x3f2aaaab);
    let exp_shifted = exp_bits >> 23;
    let mantissa = f32::from_bits((x_bits.wrapping_sub(exp_shifted << 23)) as u32);
    let exp_val = exp_shifted as f32;

    let x = mantissa - 1.0;
    eval_rational_poly(x, LOG2F_P, LOG2F_Q) + exp_val
}

// Max relative error: ~3e-5
#[inline]
pub fn fast_powf(base: f32, exp: f32) -> f32 {
    fast_pow2f(fast_log2f(base) * exp)
}

#[cfg(test)]
mod test {
    use test_log::test;

    use crate::util::test::assert_almost_eq;

    use super::*;

    #[test]
    fn test_fast_erff() {
        // Golden data generated by libjxl FastErff.
        let golden = [
            -0.796682, -0.741735, -0.677460, -0.603721, -0.520669, -0.428785, -0.328955, -0.222604,
            -0.111897, 0.000000, 0.111897, 0.222604, 0.328955, 0.428785, 0.520669, 0.603721,
            0.677460, 0.741735, 0.796682,
        ];
        for (index, f_x_10) in (-9..=9).enumerate() {
            let f = f_x_10 as f32 * 0.1;
            assert_almost_eq!(fast_erff(f), golden[index], 1e-6);
        }
    }

    #[test]
    fn test_fast_cos() {
        let golden = [
            (-6.2831854820f32, 0.9999992847f32),
            (-5.5439867973f32, 0.7390110493f32),
            (-4.8047885895f32, 0.0922695398f32),
            (-4.0655903816f32, -0.6026362181f32),
            (-3.3263921738f32, -0.9829726219f32),
            (-2.5871939659f32, -0.8502180576f32),
            (-1.8479956388f32, -0.2736620903f32),
            (-1.1087974310f32, 0.4457378387f32),
            (-0.3695991337f32, 0.9324731827f32),
            (0.3695991337f32, 0.9324731827f32),
            (1.1087974310f32, 0.4457378387f32),
            (1.8479956388f32, -0.2736620903f32),
            (2.5871939659f32, -0.8502180576f32),
            (3.3263921738f32, -0.9829726219f32),
            (4.0655903816f32, -0.6026362181f32),
            (4.8047885895f32, 0.0922695398f32),
            (5.5439867973f32, 0.7390110493f32),
            (6.2831854820f32, 0.9999992847f32),
        ];
        for (x, want) in golden {
            assert_almost_eq!(fast_cos(x), want, 1e-10);
        }
    }

    #[test]
    fn fast_powf_arb() {
        arbtest::arbtest(|u| {
            // (0.0, 128.0]
            let base = u.int_in_range(1..=1 << 24)? as f32 / (1 << 17) as f32;
            // [-8.0, 8.0]
            let exp = u.int_in_range(-(1i32 << 23)..=1 << 23)? as f32 / (1 << 20) as f32;

            let expected = base.powf(exp);
            let actual = fast_powf(base, exp);
            let abs_error = (actual - expected).abs();
            let rel_error = abs_error / expected;
            assert!(rel_error < 3e-5);
            Ok(())
        });
    }
}
